---
- name : Install Nginx
  apt:
    name: Nginx
    state: present
    update_cache: yes
- name : copy nginx config
  template:
    src: flask.conf.j2
    dest: /etc/nginx/sites-available/{{flask_project_name}}
  notify:
    - restart nginx
- name: Active Nginx configuration
  file:
    src: /etc/nginx/sites-available/{{ flask_project_name }}
    dest: /etc/nginx/sites-enabled/{{ flask_project_name }}
    state: link
    force: yes
  notify: restart nginx
- name: Remove default Nginx configuration
  file:
    src: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
