---
- name : install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes
- name : enable ports
  ufw:
    rule: allow
    port: "{{ item}}"
  loop:
    - 22
    - 80
    - 443
- name : enable firewall
  ufw:
    state: enabled
    policy: deny